unit JoinGuard;

{
  JoinGuard - catches (and repairs) the host crash when a player joins a
              battle room that already has 10+ players.

  Network_Add_Player_Remote (0x450A10) runs on the host when a player joins.
  With 10+ players in the room the game ends up executing at a bad address a
  few bytes after one of this function's calls (0x450D0C / 0x450D15 / 0x450D20
  / 0x000E0D0B), with EBX/EBP still holding this function's early values -
  i.e. one of its calls returns somewhere it should not, with a broken stack.

  Every call this function makes on the way is redirected to a stub that
  keeps the real return address and the caller's EBX/EBP/ESI/EDI in its own
  storage (so the callee cannot damage them), calls the real function, and
  then checks ESP and those registers. If anything is off it logs which call
  did it to tplayx_joinguard.log, puts everything back and returns to the
  right place.

  Generated by C:\tpLAYX1\tools\gen_joinguard.py - edit that, not this.
  Off switch without rebuilding: empty file  joinguard.off  in the game folder.
}

interface

uses
  PluginEngine;

Procedure OnInstall;
Procedure OnUninstall;

const
  State_JoinGuard : boolean = true;

function GetPlugin : TPluginData;

implementation

uses
  Windows,
  SysUtils;

type
  TGuardState = record
    Ret, Esp, Ebx, Ebp, Esi, Edi, Eax : Cardinal;
    BadEsp, BadEbx, BadEbp, BadEsi, BadEdi : Cardinal;
    Depth : Cardinal;
  end;

var
  GA, GB, GC, GD, GE, GF : TGuardState;
  LogPath    : string = '';
  Repairs    : Integer = 0;

procedure JLog(const s : string);
var
  f : TextFile;
begin
  if LogPath = '' then Exit;
  try
    AssignFile(f, LogPath);
    if FileExists(LogPath) then Append(f) else Rewrite(f);
    Writeln(f, FormatDateTime('hh:nn:ss', Now) + ' ' + s);
    CloseFile(f);
  except
  end;
end;

procedure ReportBad(const name : string; site : Cardinal; var g : TGuardState; argBytes : Cardinal);
begin
  Inc(Repairs);
  if Repairs > 200 then Exit;
  JLog(Format('REPAIRED call at %.8x (%s) #%d: ESP %.8x expected %.8x (diff %d) | ' +
              'EBX %.8x->%.8x EBP %.8x->%.8x ESI %.8x->%.8x EDI %.8x->%.8x | return %.8x',
              [site, name, Repairs, g.BadEsp, g.Esp + argBytes, Integer(g.BadEsp) - Integer(g.Esp + argBytes),
               g.Ebx, g.BadEbx, g.Ebp, g.BadEbp, g.Esi, g.BadEsi, g.Edi, g.BadEdi, g.Ret]));
end;

procedure ReportA; stdcall; begin ReportBad('HAPI_BroadcastMessage (player info)', $00450CBB, GA, 12); end;
procedure ReportB; stdcall; begin ReportBad('HAPI_BroadcastMessage (0x24 packet)', $00450CF6, GB, 12); end;
procedure ReportC; stdcall; begin ReportBad('NetQueue_Flush(1)', $00450D0B, GC, 4); end;
procedure ReportD; stdcall; begin ReportBad('HAPI_GetPlayerName -> DirectPlay GetPlayerName', $00450B6F, GD, 16); end;
procedure ReportE; stdcall; begin ReportBad('InitPlayerSlot(index,type)', $00450C29, GE, 8); end;
procedure ReportF; stdcall; begin ReportBad('GetTimeMs', $00450C3C, GF, 0); end;

// ---- stub A: call at $00450CBB -> $00451DF0  HAPI_BroadcastMessage (player info)
procedure StubA; assembler; nostackframe;
asm
  cmp  dword ptr [GA.Depth], 0
  jne  @nested
  inc  dword ptr [GA.Depth]
  pop  dword ptr [GA.Ret]
  mov  dword ptr [GA.Esp], esp
  mov  dword ptr [GA.Ebx], ebx
  mov  dword ptr [GA.Ebp], ebp
  mov  dword ptr [GA.Esi], esi
  mov  dword ptr [GA.Edi], edi
  mov  dword ptr [GA.Eax], $00451DF0
  call dword ptr [GA.Eax]
  mov  dword ptr [GA.Eax], eax
  mov  eax, dword ptr [GA.Esp]
  add  eax, 12
  cmp  esp, eax
  jne  @bad
  cmp  ebx, dword ptr [GA.Ebx]
  jne  @bad
  cmp  ebp, dword ptr [GA.Ebp]
  jne  @bad
  cmp  esi, dword ptr [GA.Esi]
  jne  @bad
  cmp  edi, dword ptr [GA.Edi]
  jne  @bad
  jmp  @done
@bad:
  mov  dword ptr [GA.BadEsp], esp
  mov  dword ptr [GA.BadEbx], ebx
  mov  dword ptr [GA.BadEbp], ebp
  mov  dword ptr [GA.BadEsi], esi
  mov  dword ptr [GA.BadEdi], edi
  mov  esp, eax
  mov  ebx, dword ptr [GA.Ebx]
  mov  ebp, dword ptr [GA.Ebp]
  mov  esi, dword ptr [GA.Esi]
  mov  edi, dword ptr [GA.Edi]
  pushad
  pushfd
  call ReportA
  popfd
  popad
@done:
  mov  eax, dword ptr [GA.Eax]
  dec  dword ptr [GA.Depth]
  jmp  dword ptr [GA.Ret]
@nested:
  push $00451DF0
  ret
end;

// ---- stub B: call at $00450CF6 -> $00451DF0  HAPI_BroadcastMessage (0x24 packet)
procedure StubB; assembler; nostackframe;
asm
  cmp  dword ptr [GB.Depth], 0
  jne  @nested
  inc  dword ptr [GB.Depth]
  pop  dword ptr [GB.Ret]
  mov  dword ptr [GB.Esp], esp
  mov  dword ptr [GB.Ebx], ebx
  mov  dword ptr [GB.Ebp], ebp
  mov  dword ptr [GB.Esi], esi
  mov  dword ptr [GB.Edi], edi
  mov  dword ptr [GB.Eax], $00451DF0
  call dword ptr [GB.Eax]
  mov  dword ptr [GB.Eax], eax
  mov  eax, dword ptr [GB.Esp]
  add  eax, 12
  cmp  esp, eax
  jne  @bad
  cmp  ebx, dword ptr [GB.Ebx]
  jne  @bad
  cmp  ebp, dword ptr [GB.Ebp]
  jne  @bad
  cmp  esi, dword ptr [GB.Esi]
  jne  @bad
  cmp  edi, dword ptr [GB.Edi]
  jne  @bad
  jmp  @done
@bad:
  mov  dword ptr [GB.BadEsp], esp
  mov  dword ptr [GB.BadEbx], ebx
  mov  dword ptr [GB.BadEbp], ebp
  mov  dword ptr [GB.BadEsi], esi
  mov  dword ptr [GB.BadEdi], edi
  mov  esp, eax
  mov  ebx, dword ptr [GB.Ebx]
  mov  ebp, dword ptr [GB.Ebp]
  mov  esi, dword ptr [GB.Esi]
  mov  edi, dword ptr [GB.Edi]
  pushad
  pushfd
  call ReportB
  popfd
  popad
@done:
  mov  eax, dword ptr [GB.Eax]
  dec  dword ptr [GB.Depth]
  jmp  dword ptr [GB.Ret]
@nested:
  push $00451DF0
  ret
end;

// ---- stub C: call at $00450D0B -> $004618A0  NetQueue_Flush(1)
procedure StubC; assembler; nostackframe;
asm
  cmp  dword ptr [GC.Depth], 0
  jne  @nested
  inc  dword ptr [GC.Depth]
  pop  dword ptr [GC.Ret]
  mov  dword ptr [GC.Esp], esp
  mov  dword ptr [GC.Ebx], ebx
  mov  dword ptr [GC.Ebp], ebp
  mov  dword ptr [GC.Esi], esi
  mov  dword ptr [GC.Edi], edi
  mov  dword ptr [GC.Eax], $004618A0
  call dword ptr [GC.Eax]
  mov  dword ptr [GC.Eax], eax
  mov  eax, dword ptr [GC.Esp]
  add  eax, 4
  cmp  esp, eax
  jne  @bad
  cmp  ebx, dword ptr [GC.Ebx]
  jne  @bad
  cmp  ebp, dword ptr [GC.Ebp]
  jne  @bad
  cmp  esi, dword ptr [GC.Esi]
  jne  @bad
  cmp  edi, dword ptr [GC.Edi]
  jne  @bad
  jmp  @done
@bad:
  mov  dword ptr [GC.BadEsp], esp
  mov  dword ptr [GC.BadEbx], ebx
  mov  dword ptr [GC.BadEbp], ebp
  mov  dword ptr [GC.BadEsi], esi
  mov  dword ptr [GC.BadEdi], edi
  mov  esp, eax
  mov  ebx, dword ptr [GC.Ebx]
  mov  ebp, dword ptr [GC.Ebp]
  mov  esi, dword ptr [GC.Esi]
  mov  edi, dword ptr [GC.Edi]
  pushad
  pushfd
  call ReportC
  popfd
  popad
@done:
  mov  eax, dword ptr [GC.Eax]
  dec  dword ptr [GC.Depth]
  jmp  dword ptr [GC.Ret]
@nested:
  push $004618A0
  ret
end;

// ---- stub D: call at $00450B6F -> $004CA7C0  HAPI_GetPlayerName -> DirectPlay GetPlayerName
procedure StubD; assembler; nostackframe;
asm
  cmp  dword ptr [GD.Depth], 0
  jne  @nested
  inc  dword ptr [GD.Depth]
  pop  dword ptr [GD.Ret]
  mov  dword ptr [GD.Esp], esp
  mov  dword ptr [GD.Ebx], ebx
  mov  dword ptr [GD.Ebp], ebp
  mov  dword ptr [GD.Esi], esi
  mov  dword ptr [GD.Edi], edi
  mov  dword ptr [GD.Eax], $004CA7C0
  call dword ptr [GD.Eax]
  mov  dword ptr [GD.Eax], eax
  mov  eax, dword ptr [GD.Esp]
  add  eax, 16
  cmp  esp, eax
  jne  @bad
  cmp  ebx, dword ptr [GD.Ebx]
  jne  @bad
  cmp  ebp, dword ptr [GD.Ebp]
  jne  @bad
  cmp  esi, dword ptr [GD.Esi]
  jne  @bad
  cmp  edi, dword ptr [GD.Edi]
  jne  @bad
  jmp  @done
@bad:
  mov  dword ptr [GD.BadEsp], esp
  mov  dword ptr [GD.BadEbx], ebx
  mov  dword ptr [GD.BadEbp], ebp
  mov  dword ptr [GD.BadEsi], esi
  mov  dword ptr [GD.BadEdi], edi
  mov  esp, eax
  mov  ebx, dword ptr [GD.Ebx]
  mov  ebp, dword ptr [GD.Ebp]
  mov  esi, dword ptr [GD.Esi]
  mov  edi, dword ptr [GD.Edi]
  pushad
  pushfd
  call ReportD
  popfd
  popad
@done:
  mov  eax, dword ptr [GD.Eax]
  dec  dword ptr [GD.Depth]
  jmp  dword ptr [GD.Ret]
@nested:
  push $004CA7C0
  ret
end;

// ---- stub E: call at $00450C29 -> $00464290  InitPlayerSlot(index,type)
procedure StubE; assembler; nostackframe;
asm
  cmp  dword ptr [GE.Depth], 0
  jne  @nested
  inc  dword ptr [GE.Depth]
  pop  dword ptr [GE.Ret]
  mov  dword ptr [GE.Esp], esp
  mov  dword ptr [GE.Ebx], ebx
  mov  dword ptr [GE.Ebp], ebp
  mov  dword ptr [GE.Esi], esi
  mov  dword ptr [GE.Edi], edi
  mov  dword ptr [GE.Eax], $00464290
  call dword ptr [GE.Eax]
  mov  dword ptr [GE.Eax], eax
  mov  eax, dword ptr [GE.Esp]
  add  eax, 8
  cmp  esp, eax
  jne  @bad
  cmp  ebx, dword ptr [GE.Ebx]
  jne  @bad
  cmp  ebp, dword ptr [GE.Ebp]
  jne  @bad
  cmp  esi, dword ptr [GE.Esi]
  jne  @bad
  cmp  edi, dword ptr [GE.Edi]
  jne  @bad
  jmp  @done
@bad:
  mov  dword ptr [GE.BadEsp], esp
  mov  dword ptr [GE.BadEbx], ebx
  mov  dword ptr [GE.BadEbp], ebp
  mov  dword ptr [GE.BadEsi], esi
  mov  dword ptr [GE.BadEdi], edi
  mov  esp, eax
  mov  ebx, dword ptr [GE.Ebx]
  mov  ebp, dword ptr [GE.Ebp]
  mov  esi, dword ptr [GE.Esi]
  mov  edi, dword ptr [GE.Edi]
  pushad
  pushfd
  call ReportE
  popfd
  popad
@done:
  mov  eax, dword ptr [GE.Eax]
  dec  dword ptr [GE.Depth]
  jmp  dword ptr [GE.Ret]
@nested:
  push $00464290
  ret
end;

// ---- stub F: call at $00450C3C -> $004B6340  GetTimeMs
procedure StubF; assembler; nostackframe;
asm
  cmp  dword ptr [GF.Depth], 0
  jne  @nested
  inc  dword ptr [GF.Depth]
  pop  dword ptr [GF.Ret]
  mov  dword ptr [GF.Esp], esp
  mov  dword ptr [GF.Ebx], ebx
  mov  dword ptr [GF.Ebp], ebp
  mov  dword ptr [GF.Esi], esi
  mov  dword ptr [GF.Edi], edi
  mov  dword ptr [GF.Eax], $004B6340
  call dword ptr [GF.Eax]
  mov  dword ptr [GF.Eax], eax
  mov  eax, dword ptr [GF.Esp]
  add  eax, 0
  cmp  esp, eax
  jne  @bad
  cmp  ebx, dword ptr [GF.Ebx]
  jne  @bad
  cmp  ebp, dword ptr [GF.Ebp]
  jne  @bad
  cmp  esi, dword ptr [GF.Esi]
  jne  @bad
  cmp  edi, dword ptr [GF.Edi]
  jne  @bad
  jmp  @done
@bad:
  mov  dword ptr [GF.BadEsp], esp
  mov  dword ptr [GF.BadEbx], ebx
  mov  dword ptr [GF.BadEbp], ebp
  mov  dword ptr [GF.BadEsi], esi
  mov  dword ptr [GF.BadEdi], edi
  mov  esp, eax
  mov  ebx, dword ptr [GF.Ebx]
  mov  ebp, dword ptr [GF.Ebp]
  mov  esi, dword ptr [GF.Esi]
  mov  edi, dword ptr [GF.Edi]
  pushad
  pushfd
  call ReportF
  popfd
  popad
@done:
  mov  eax, dword ptr [GF.Eax]
  dec  dword ptr [GF.Depth]
  jmp  dword ptr [GF.Ret]
@nested:
  push $004B6340
  ret
end;

// -----------------------------------------------------------------------------
// If a guarded callee never comes back to its stub (it "returns" somewhere
// else and the game faults), the stub's Depth is still 1. The exception
// handler below finds that stub, logs it, and resumes the game exactly as if
// the call had returned normally: ESP/EBX/EBP/ESI/EDI from the stub's copy,
// EAX = the call's normal success value, EIP = the real return address.
// -----------------------------------------------------------------------------
type
  TGuardRef = record
    G : ^TGuardState; Name : string; Site, ArgBytes, OkEax : Cardinal;
  end;

function MyAddVEH(First : ULONG; Handler : Pointer) : Pointer; stdcall;
  external 'kernel32.dll' name 'AddVectoredExceptionHandler';
function MyRemoveVEH(Handle : Pointer) : ULONG; stdcall;
  external 'kernel32.dll' name 'RemoveVectoredExceptionHandler';

var
  VehHandle  : Pointer = nil;
  Recoveries : Integer = 0;

function GuardRef(i : Integer) : TGuardRef;
begin
  case i of
    0: begin result.G := @GA; result.Name := 'HAPI_BroadcastMessage (player info)'; result.Site := $00450CBB; result.ArgBytes := 12; result.OkEax := 0; end;
    1: begin result.G := @GB; result.Name := 'HAPI_BroadcastMessage (0x24 packet)'; result.Site := $00450CF6; result.ArgBytes := 12; result.OkEax := 0; end;
    2: begin result.G := @GC; result.Name := 'NetQueue_Flush(1)'; result.Site := $00450D0B; result.ArgBytes := 4; result.OkEax := 0; end;
    3: begin result.G := @GD; result.Name := 'HAPI_GetPlayerName -> DirectPlay GetPlayerName'; result.Site := $00450B6F; result.ArgBytes := 16; result.OkEax := 0; end;
    4: begin result.G := @GE; result.Name := 'InitPlayerSlot(index,type)'; result.Site := $00450C29; result.ArgBytes := 8; result.OkEax := 0; end;
    5: begin result.G := @GF; result.Name := 'GetTimeMs'; result.Site := $00450C3C; result.ArgBytes := 0; result.OkEax := 0; end;
  else
    result.G := nil;
  end;
end;

function JoinGuardVeh(ep : PExceptionPointers) : LongInt; stdcall;
var
  i, k : Integer;
  r : TGuardRef;
  c : PContext;
  code : Cardinal;
  s : string;
begin
  result := 0;                              // EXCEPTION_CONTINUE_SEARCH
  code := ep^.ExceptionRecord^.ExceptionCode;
  if (code <> $C0000005) and (code <> $C000001D) and (code <> $C0000096) then Exit;
  c := ep^.ContextRecord;
  // only the join-crash pattern: executing inside Network_Add_Player_Remote's
  // body at a bad spot, or at a garbage address below the exe
  if not (((c^.Eip >= $00450A10) and (c^.Eip < $00450D80)) or (c^.Eip < $00400000)) then Exit;
  for i := 0 to 5 do
  begin
    r := GuardRef(i);
    if (r.G = nil) or (r.G^.Depth = 0) then Continue;
    Inc(Recoveries);
    s := Format('CAUGHT: call at %.8x (%s) never returned to its stub - fault %.8x at EIP %.8x | ' +
                'EAX %.8x EBX %.8x ECX %.8x EDX %.8x ESI %.8x EDI %.8x EBP %.8x ESP %.8x (stub ESP %.8x)',
                [r.Site, r.Name, code, c^.Eip, c^.Eax, c^.Ebx, c^.Ecx, c^.Edx, c^.Esi, c^.Edi, c^.Ebp, c^.Esp, r.G^.Esp]);
    JLog(s);
    s := 'stack at fault:';
    for k := -4 to 23 do
      if not IsBadReadPtr(Pointer(c^.Esp + Cardinal(k * 4)), 4) then
        s := s + Format(' %.8x', [PCardinal(c^.Esp + Cardinal(k * 4))^]);
    JLog(s);
    if Recoveries > 20 then
    begin
      JLog('too many recoveries this session - letting the game crash');
      Exit;
    end;
    c^.Esp := r.G^.Esp + r.ArgBytes;
    c^.Ebx := r.G^.Ebx;
    c^.Ebp := r.G^.Ebp;
    c^.Esi := r.G^.Esi;
    c^.Edi := r.G^.Edi;
    c^.Eax := r.OkEax;
    c^.Eip := r.G^.Ret;
    r.G^.Depth := 0;
    JLog(Format('resumed at %.8x as if the call had returned', [r.G^.Ret]));
    result := -1;                           // EXCEPTION_CONTINUE_EXECUTION
    Exit;
  end;
end;


function CallTargetIs(site, target : Cardinal) : boolean;
begin
  result := (PByte(site)^ = $E8) and
            (Cardinal(LongInt(site + 5) + PLongInt(site + 1)^) = target);
end;

Procedure OnInstall;
begin
  LogPath := ExtractFilePath(ParamStr(0)) + 'tplayx_joinguard.log';
  JLog('JoinGuard active: 6 calls in Network_Add_Player_Remote guarded');
  if VehHandle = nil then
    VehHandle := MyAddVEH(1, @JoinGuardVeh);
end;

Procedure OnUninstall;
begin
  if VehHandle <> nil then
  begin
    MyRemoveVEH(VehHandle);
    VehHandle := nil;
  end;
  if Repairs > 0 then
    JLog(Format('session end: %d stack repair(s)', [Repairs]));
end;

function GetPlugin : TPluginData;
begin
  result := nil;
  if not State_JoinGuard then Exit;
  if FileExists(ExtractFilePath(ParamStr(0)) + 'joinguard.off') then Exit;
  if not (CallTargetIs($00450CBB, $00451DF0) and
          CallTargetIs($00450CF6, $00451DF0) and
          CallTargetIs($00450D0B, $004618A0) and
          CallTargetIs($00450B6F, $004CA7C0) and
          CallTargetIs($00450C29, $00464290) and
          CallTargetIs($00450C3C, $004B6340)) then Exit;

  result := TPluginData.create( true,
                                'Join guard (16P join stack repair)',
                                State_JoinGuard,
                                @OnInstall, @OnUninstall );
  result.MakeStaticCall(State_JoinGuard, 'JoinGuard A', @StubA, $00450CBB);
  result.MakeStaticCall(State_JoinGuard, 'JoinGuard B', @StubB, $00450CF6);
  result.MakeStaticCall(State_JoinGuard, 'JoinGuard C', @StubC, $00450D0B);
  result.MakeStaticCall(State_JoinGuard, 'JoinGuard D', @StubD, $00450B6F);
  result.MakeStaticCall(State_JoinGuard, 'JoinGuard E', @StubE, $00450C29);
  result.MakeStaticCall(State_JoinGuard, 'JoinGuard F', @StubF, $00450C3C);
end;

end.
